repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types_or: [ python, pyi ]
        args: [ "--ignore-missing-imports", "--scripts-are-modules", "--check-untyped-defs" ]

      - id: ruff-check
        name: ruff-check
        entry: ruff check
        language: python
        types_or: [ python, pyi ]
        args: [ "--fix" ]

      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: python
        types_or: [ python, pyi ]
