# Generated by Django 5.1.3 on 2024-11-29 21:50

import django.db.models.deletion
import src_back.models.login_token
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=src_back.models.login_token.get_created_at
                    ),
                ),
                (
                    "expired_at",
                    models.DateTimeField(
                        default=src_back.models.login_token.get_expired_at
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("token",), name="unique_login_token__token"
                    )
                ],
            },
        ),
    ]
